Update package.json
Specify the file after the build. Library of the user, because that are not necessarily using the module loader and transformer compiler with the same settings as the author.

my uglify is ignore /node_modules, so show error at
https://github.com/David-Desmaisons/Vue.Isotope/blob/861683cdc246a55dfd2b3caa8ab753b01aa55b94/src/vue_isotope.js#L35

```
SyntaxError: Unexpected token punc «,», expected punc «:»
```